// Mock data for hackathons
export const mockHackathons = [
  {
    id: 1,
    name: "Tech India Innovate 2024",
    date: "2024-10-15",
    location: "Bengaluru, Karnataka",
    type: "offline",
    description: "Build the next generation of web applications with cutting-edge technology.",
    participants: 234,
    image: "/tech-conference.png",
  },
  {
    id: 2,
    name: "AI Bharat Hackathon",
    date: "2024-11-20",
    location: "Online",
    type: "online",
    description: "Create innovative AI solutions to solve real-world problems.",
    participants: 567,
    image: "/ai-digital.jpg",
  },
  {
    id: 3,
    name: "Healthcare Innovation Sprint India",
    date: "2024-12-05",
    location: "Mumbai, Maharashtra",
    type: "offline",
    description: "Transform healthcare through technology and innovation.",
    participants: 189,
    image: "/healthcare-tech.jpg",
  },
  {
    id: 4,
    name: "Web3 India Summit",
    date: "2024-12-18",
    location: "Online",
    type: "online",
    description: "Build decentralized applications on blockchain technology.",
    participants: 423,
    image: "/blockchain-web3.jpg",
  },
  {
    id: 5,
    name: "Mobile App Challenge India",
    date: "2025-01-10",
    location: "Hyderabad, Telangana",
    type: "offline",
    description: "Create the next viral mobile application in 48 hours.",
    participants: 312,
    image: "/mobile-app-showcase.png",
  },
  {
    id: 6,
    name: "Climate Tech Hackathon India",
    date: "2025-01-25",
    location: "Online",
    type: "online",
    description: "Build sustainable solutions for climate change challenges.",
    participants: 289,
    image: "/climate-environment.jpg",
  },
]

// Mock data for users
export const mockUsers = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    skills: ["React", "Node.js", "MongoDB"],
    bio: "Full-stack developer passionate about building scalable web applications.",
    avatar: "/developer-portrait.png",
    lookingForTeam: true,
  },
  {
    id: 2,
    name: "Priya Kapoor",
    email: "priya.kapoor@example.com",
    skills: ["UI/UX Design", "Figma", "Product Design"],
    bio: "Product designer focused on creating intuitive user experiences.",
    avatar: "/designer-portrait.png",
    lookingForTeam: true,
  },
  {
    id: 3,
    name: "Twinkle Sharma",
    email: "twinkle.sharma@example.com",
    skills: ["Python", "Machine Learning", "Data Science"],
    bio: "ML engineer interested in applying AI to solve real-world problems.",
    avatar: "/data-scientist-workspace.png",
    lookingForTeam: true,
  },
  {
    id: 4,
    name: "Ananya Iyer",
    email: "ananya.iyer@example.com",
    skills: ["Marketing", "Content Strategy", "Social Media"],
    bio: "Marketing specialist helping teams craft compelling narratives.",
    avatar: "/marketing-professional.png",
    lookingForTeam: true,
  },
  {
    id: 5,
    name: "Kabir Singh",
    email: "kabir.singh@example.com",
    skills: ["Flutter", "Swift", "Mobile Development"],
    bio: "Mobile developer with 5 years of experience in iOS and Android.",
    avatar: "/mobile-developer.png",
    lookingForTeam: true,
  },
  {
    id: 6,
    name: "Rohan",
    email: "sneha.reddy@example.com",
    skills: ["DevOps", "AWS", "Docker"],
    bio: "DevOps engineer specializing in cloud infrastructure and automation.",
    avatar: "/thoughtful-engineer.png",
    lookingForTeam: true,
  },
]

// Mock data for teams
export const mockTeams = [
  {
    id: 1,
    name: "Tech Innovators",
    hackathonId: 1,
    members: [1, 2],
    needsSkills: ["Backend Developer", "Data Scientist"],
    description: "Building an AI-powered productivity tool.",
  },
  {
    id: 2,
    name: "Code Warriors",
    hackathonId: 2,
    members: [3],
    needsSkills: ["Frontend Developer", "UI Designer"],
    description: "Creating a machine learning platform for beginners.",
  },
  {
    id: 3,
    name: "Health Tech Squad",
    hackathonId: 3,
    members: [4, 5],
    needsSkills: ["Full Stack Developer"],
    description: "Developing a telemedicine application.",
  },
]
