// Mock data for hackathons
export const mockHackathons = [
  {
    id: 1,
    name: "Tech India Innovate 2026",
    date: "2026-1-15",
    location: "Bengaluru, Karnataka",
    type: "offline",
    description: "Build the next generation of web applications with cutting-edge technology.",
    participants: 234,
    image: "/tech-conference.png",
  },
  {
    id: 2,
    name: "AI Bharat Hackathon",
    date: "2025-11-20",
    location: "Online",
    type: "online",
    description: "Create innovative AI solutions to solve real-world problems.",
    participants: 567,
    image: "/ai-digital.jpg",
  },
  {
    id: 3,
    name: "Healthcare Innovation Sprint India",
    date: "2026-1-01",
    location: "Mumbai, Maharashtra",
    type: "offline",
    description: "Transform healthcare through technology and innovation.",
    participants: 189,
    image: "/healthcare-tech.jpg",
  },
  {
    id: 4,
    name: "Web3 India Summit",
    date: "2025-12-18",
    location: "Online",
    type: "online",
    description: "Build decentralized applications on blockchain technology.",
    participants: 423,
    image: "/blockchain-web3.jpg",
  },
  {
    id: 5,
    name: "Mobile App Challenge India",
    date: "2026-01-10",
    location: "Hyderabad, Telangana",
    type: "offline",
    description: "Create the next viral mobile application in 48 hours.",
    participants: 312,
    image: "/mobile-app-showcase.png",
  },
  {
    id: 6,
    name: "Climate Tech Hackathon India",
    date: "2025-01-25",
    location: "Online",
    type: "online",
    description: "Build sustainable solutions for climate change challenges.",
    participants: 289,
    image: "/climate-environment.jpg",
  },
  {
    id: 7,
    name: "GenAI Revolution Challenge",
    date: "2026-02-15",
    location: "Pune, Maharashtra",
    type: "offline",
    description: "Explore the potential of Generative AI to create content and code.",
    participants: 450,
    image: "/genai.jpg",
  },
  {
    id: 8,
    name: "CyberGuard Zero Trust 2025",
    date: "2026-03-05",
    location: "Online",
    type: "online",
    description: "Defend systems against next-gen threats using Zero Trust architecture.",
    participants: 600,
    image: "/cyberguard.jpg",
  },
  {
    id: 9,
    name: "Quantum Leap India",
    date: "2026-03-20",
    location: "Bengaluru, Karnataka",
    type: "offline",
    description: "Harness the power of quantum computing to solve complex algorithms.",
    participants: 150,
    image: "/quantumleap.jpg",
  },
  {
    id: 10,
    name: "Fintech Nexus Summit",
    date: "2026-04-10",
    location: "Mumbai, Maharashtra",
    type: "offline",
    description: "Revolutionize digital payments and decentralized finance solutions.",
    participants: 520,
    image: "/fintech nexus.jpg",
  },
  {
    id: 11,
    name: "AR/VR Odyssey Hack",
    date: "2025-04-25",
    location: "Online",
    type: "online",
    description: "Build immersive experiences for the metaverse and spatial computing.",
    participants: 380,
    image: "/AR.jpg",
  },
  {
    id: 12,
    name: "NextGen EdTech Hackathon",
    date: "2025-05-15",
    location: "Online",
    type: "online",
    description: "Create the future of learning with interactive and personalized AI tutors.",
    participants: 410,
    image: "/nextgen.jpg",
  }
]

// Mock data for users
export const mockUsers = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    skills: ["React", "Node.js", "MongoDB"],
    bio: "Full-stack developer passionate about building scalable web applications.",
    avatar: "/developer-portrait.png",
    lookingForTeam: true,
  },
  {
    id: 2,
    name: "Priya Verma",
    email: "priya.verma@example.com",
    skills: ["UI/UX Design", "Figma", "Product Design"],
    bio: "Product designer focused on creating intuitive user experiences.",
    avatar: "/designer-portrait.png",
    lookingForTeam: true,
  },
  {
    id: 3,
    name: "Tina Sharma",
    email: "tina.sharma@example.com",
    skills: ["Python", "Machine Learning", "Data Science"],
    bio: "ML engineer interested in applying AI to solve real-world problems.",
    avatar: "/data-scientist-workspace.png",
    lookingForTeam: true,
  },
  {
    id: 4,
    name: "Ananya Iyer",
    email: "ananya.iyer@example.com",
    skills: ["Marketing", "Content Strategy", "Social Media"],
    bio: "Marketing specialist helping teams craft compelling narratives.",
    avatar: "/marketing-professional.png",
    lookingForTeam: true,
  },
  {
    id: 5,
    name: "Kabir Singh",
    email: "kabir.singh@example.com",
    skills: ["Flutter", "Swift", "Mobile Development"],
    bio: "Mobile developer with 5 years of experience in iOS and Android.",
    avatar: "/mobile-developer.png",
    lookingForTeam: true,
  },
  {
    id: 6,
    name: "Rohan",
    email: "sneha.reddy@example.com",
    skills: ["DevOps", "AWS", "Docker"],
    bio: "DevOps engineer specializing in cloud infrastructure and automation.",
    avatar: "/thoughtful-engineer.png",
    lookingForTeam: true,
  },
]

// Mock data for teams
export const mockTeams = [
  {
    id: 1,
    name: "Tech Innovators",
    hackathonId: 1,
    members: [1, 2],
    needsSkills: ["Backend Developer", "Data Scientist"],
    description: "Building an AI-powered productivity tool.",
  },
  {
    id: 2,
    name: "Code Warriors",
    hackathonId: 2,
    members: [3],
    needsSkills: ["Frontend Developer", "UI Designer"],
    description: "Creating a machine learning platform for beginners.",
  },
  {
    id: 3,
    name: "Health Tech Squad",
    hackathonId: 3,
    members: [4, 5],
    needsSkills: ["Full Stack Developer"],
    description: "Developing a telemedicine application.",
  },
]
